spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml

server:
  port: 8083

#dubbo:
#  protocol:
#    port: 20889
#  application:
#    qos-port: 33333
