logging:
  level:
    root: info
    #关闭nacos心跳日志
    com.alibaba.nacos.client.*: WARN



spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml,classpath:rpc.yml

server:
  port: 8181

#dubbo:
#  protocol:
#    port: 20889
#  application:
#    qos-port: 33333
