logging:
  level:
    root: info


spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml

server:
  port: 8082

#dubbo:
#  protocol:
#    port: 20889
#  application:
#    qos-port: 33333
