spring:
  data:
    redis:
      # Redis服务器地址
      host: ${coderChat.redis.host}
      # Redis服务器端口号
      port: ${coderChat.redis.port}
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${coderChat.redis.password}
    jackson:
      serialization:
        write-dates-as-timestamps: true
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000